export interface PanelFlyoutData {
    userInfo: any
    flyoutConfig: any
    isError: boolean
    isUnsupportedCountry: boolean
    errorMessage: any
    isRewardsUser: boolean
    isDarkMode: boolean
    flyoutResult: FlyoutResult
    channel: string
    userId: string
    testHookDate: any
    isVisualParityTest: boolean
    loggingContext: any
    partnerId: string
    language: string
    partnerInfo: any
    localizedStrings: any
    additionalParameters: any
    additionalParametersStringForEnrollUrl: any
    additionalParametersStringForOfferUrl: any
    additionalParametersStringForAjaxCall: any
    isLiftedSearchCapAutoClaimEnabled: number
    isLiftedSearchCapAutoClaimSuccessful: boolean
    showAADLinkingExperience: boolean
    featureNames: string
    isMobileOnlyPartner: boolean
}

export interface FlyoutResult {
    userStatus: FlyoutUserStatus
    userGoal: any
    userAutoRedeemItem: any
    userAutoRedeemType: any
    userOrders: any[]
    isAutoRedeemEligible: boolean
    highValueActionPromotions: FlyoutPromotion[]
    edgeHighValueActionPromotions: any[]
    browseStreakPromotions: any[]
    edgeAcquisitionPromotion: any
    dailySetPromotions: { [key: string]: FlyoutPromotion[] }
    streakPromotion: any
    acquisitionPromotion: any
    onboardingPromotion: any
    searchAndEarnPromotion: any
    streakBonusPromotions: any[]
    exploreOnBingPromotions: any[]
    impressionPromotions: any[]
    searchStreakPromotion: any
    dailyCheckInPromotion: any
    bingTrialStreakPromotion: any
    oneTimeStreakPromotion: any
    morePromotions: FlyoutPromotion[]
    machineTranslationPromo: any
    streakProtectionPromo: any
    autoRedeemPromotion: any
    onboardingChecklistPromotions: any[]
    goalCardPromotion: any
    onboardingChecklistBonusPromotion: any
    l2Context: any
    layout: any
    traceId: string
    joinUrl: string
    rebatesJoinUrl: any
    profile: any
    flyoutCatalogItem: any
    exploreOnBingAnyCardCompletionPromotion: any
    isExploreOnBingChecklistCardActivated: boolean
    shouldUseSlimStyleForCompletedPromotions: boolean
    shouldOpenInNewTab: any
    pointClaimCardPromotion: any
    suggestedSearches: any
    featureNames: string
    isLiftSearchCapAutoClaimEnabled: number
    isLiftSearchCapAutoClaimSuccessful: boolean
    levelInfoPromotion: any
    levelBenefitsPromotion: any
}

export interface FlyoutUserStatus {
    availablePoints: number
    lifetimePoints: number
    lifetimeGivingPoints: number
    lifetimePointsRedeemed: number
    counters: any
    rebateProfile: any
    oldBalance: number
    totalBalance: number
    goalBalance: number
    balanceUpdated: boolean
    isRewardsUser: boolean
}

export interface FlyoutPromotion {
    name: string
    priority: number
    isRewardable: boolean
    activityType: string
    hash: string
    attributes: any
    offerId: string
    complete: boolean
    activityProgress: number
    activityProgressMax: number
    pointProgressMax: number
    pointProgress: number
    promotionType: string
    promotionSubtype: string
    title: string
    description: string
    descriptionParam: string
    showcaseTitle: string
    showcaseDescription: string
    imageUrl: string
    smallImageUrl: string
    backgroundImageUrl: string
    showcaseBackgroundImageUrl: string
    showcaseBackgroundLargeImageUrl: string
    iconUrl: string
    animatedIconUrl: string
    animatedLargeBackgroundImageUrl: string
    destinationUrl: string
    linkText: string
    isRecurring: boolean
    isHidden: boolean
    level: string
    slidesCount: number
    legalText: string
    legalLinkText: string
    machineTranslation: string
    showUnsupportedLangNote: string
    target: string
    rewardable: boolean
    exclusiveLockedFeatureCategory: string
    exclusiveLockedFeatureStatus: string
    exclusiveLockedFeatureDestinationUrl: string
    lockedImage: string
    shouldScrollToTarget: boolean
    inProgress: string
    sectionalOrdering: number
    isAnimatedRewardEnabled: boolean
}
